// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRideTrackerWebApp.Data;

namespace MyRideTrackerWebApp.Migrations
{
    [DbContext(typeof(RideDbContext))]
    [Migration("20200529193836_AddedServiceBoolFlag")]
    partial class AddedServiceBoolFlag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyRideTrackerWebApp.Models.Ride", b =>
                {
                    b.Property<int>("RideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FillUp")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Gallons")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MapMiles")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("MileageEnd")
                        .HasColumnType("int");

                    b.Property<int>("MileageStart")
                        .HasColumnType("int");

                    b.Property<decimal?>("MilesPerGallon")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("PricePerGallon")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime>("RideDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RideRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Service")
                        .HasColumnType("bit");

                    b.Property<int>("TotalMiles")
                        .HasColumnType("int");

                    b.HasKey("RideId");

                    b.ToTable("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
